# Eclipse Temurin은 OpenJDK의 공식 배포판입니다
FROM eclipse-temurin:17-jdk

# 빌드된 JAR 파일을 컨테이너로 복사
COPY build/libs/*SNAPSHOT.jar /app.jar

# 애플리케이션 포트 노출
EXPOSE 8080

# 애플리케이션 실행
ENTRYPOINT ["java", "-jar", "/app.jar"]